spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true # enabled for accessing by docker deployment profile
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info