spring:
  h2:
    console:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
springdoc:
  packages-to-scan: com.zoomcare.candidatechallenge.controller
  swagger-ui:
    path: /api-docs
