spring:
  h2:
    console:
      enabled: true
  datasource:
    jdbcUrl: jdbc:h2:mem:testdb
    username: sa
    password:
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always