spring:
  h2:
    console:
      enabled: true
  data:
    rest:
      basePath: /api
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always